### model
model_name_or_path: /home/qwu/tmp/LLM-Research/Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: imdb_train
template: llama3
cutoff_len: 1024
max_samples: 25000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3
logging_steps: 100
save_steps: 5000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500
